version: '3.8'

services:
  optimizing-with-rag-db:
    image: pgvector/pgvector:pg16
    container_name: optimizing-with-rag-db
    environment:
      POSTGRES_DB: optimizing-with-rag-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama  # Bind host directory to container directory
    restart: unless-stopped
    entrypoint: >
      sh -c "ollama serve & sleep 5 && ollama pull llama3.1:latest && tail -f /dev/null"

volumes:
  pgvector_data:
  ollama_data:
    driver: local
